### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by RobinUS2**
Prevents hanging for very long times on connectivity issues

### CODE REVIEW

**Comment by RobinUS2** [comment]
@huyanping do you see any chance to merge this into your repo? think it's also helpful for others

**Comment by bazingarj** [comment]
Please approve this request, Time is basic thing to setup in any connect over network project

**Review by AmitKannaujiya — COMMENTED** [review]
Please merge this

**Comment by bazingarj** [comment]
Since there was no update , I cloned it made made the change here: https://github.com/bazingarj/redis-sentinel

**Comment by white-poto** [comment]
Version 0.3.1 has been released

**Pull request merged**
